version: '3'
services:
  db_users:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kmp_users
      POSTGRES_PASSWORD: kmp_users
      POSTGRES_DB: kmp_users

  app_users:
    image: epamsesegvanchikova/users:v1
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://172.18.0.2:5432/kmp_users
    depends_on:
      db_users:
        condition: service_started
