server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/kmp_users}
    username: ${POSTGRES_USER:kmp_users}
    password: ${POSTGRES_PASSWORD:kmp_users}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  db:
    changeLog: "classpath:db/changelog-master.yml"